manual update

diff --git a/scripts/alarm/app b/scripts/alarm/app
--- a/scripts/alarm/app
+++ b/scripts/alarm/app
@@ -11,6 +11,7 @@
 	# Current: Put keyboard in a different room
 	# Advanced: Implement QR Code / Geolocation unlocking
 
+
 # Declare the paths to the mp3 files as variables
 soothing_file="$HOME/nextcloud/media/music/soothing/weightless.mp3"
 normal_file="$HOME/nextcloud/media/music/regular/resonance.opus"
@@ -20,21 +21,6 @@ force_file="$HOME/nextcloud/media/music/force/wake-up.mp3"
 soothing_volume=30
 normal_volume=70
 force_volume=100
-
-
-# Check if time is given as input
-if [ $# -eq 0 ]
-then
-	# Ask the user to enter time if no input is given
-	read -p "Do you want to schedule the alarm in 8 hours? [y/n]: " answer
-	if [ "$answer" == "y" ]; then
-		time=$(date --date='8 hours' +%H:%M)
-	else
-		read -p "Enter the time for the alarm in 24h format (HH:MM): " time
-	fi
-else
-    time=$1
-fi
 
 check_dependencies() {
 	# Check if mpv is installed
@@ -49,6 +35,36 @@ check_dependencies() {
 		echo "Error: ncurses is not installed. Please install ncurses before running this script."
 		exit 1
 	fi
+}
+
+# Provide brief description on usage
+parse_args() {
+
+	# Check if time is given as input
+	if [ $# -eq 0 ]
+	then
+		# Ask the user to enter time if no input is given
+		read -p "Do you want to schedule the alarm in 8 hours? [y/n]: " answer
+		if [ "$answer" == "y" ]; then
+			time=$(date --date='8 hours' +%H:%M)
+		else
+			read -p "Enter the time for the alarm in 24h format (HH:MM): " time
+		fi
+	else
+		time=$1
+		fi
+}
+
+validate_time() {
+    # Regular expression to match the time format (HH:MM)
+    local time_regex="^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$"
+
+    if [[ $time =~ $time_regex ]]; then
+		return 0
+    else
+        echo "Invalid input. Please use the format HH:MM (e.g. 14:30)"
+		exit 1
+    fi
 }
 
 check_files() {
@@ -101,6 +117,8 @@ confirm_schedule() {
 # Main Function
 main() {
 	check_dependencies
+	parse_args
+	validate_time
 	check_files
 	schedule_alarm
 	confirm_schedule
@@ -110,3 +128,5 @@ main() {
 if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
     main
 fi
+
+
